{{ if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-frontend
  labels:
    prometheus: frontend
spec:
  serviceMonitors:
  - selector:
    matchLabels:
      {{ include "cardano.labels" . }}
{{- end -}}
