---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "cardano.fullname" . }}
  labels:
    {{- include "cardano.labels" . | nindent 4 }}
  {{- with .Values.storage.annotations }}
  annotations:
    {{- toYaml . | indent 4 }}
  {{- end }}
  {{- with .Values.storage.finalizers }}
  finalizers:
    {{ toYaml . }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.storage.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
    {{- if .Values.storage.storageClassName }}
    storageClassName: {{ .Values.storage.storageClassName }}
    {{- end }}
    {{- with .Values.storage.selectorLabels }}
    selector:
      matchLabels:
      {{- toYaml . | indent 6 }}
    {{- end }}
