---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cardano.fullname" . }}
data:
  mainnet-topology.json: |
    {{- include "cardano.topologyJson" . | indent 4 }}
  testnet-topology.json: |
    {{- include "cardano.topologyJson" . | indent 4 }}
