---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cardano.fullname" . }}
  labels:
    {{- include "cardano.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{- toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.ports.rpc.port }}
    protocol: TCP
    name: tcp
  selector:
    {{- include "cardano.selectorLabels" . | nindent 4 }}
