---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cardano.fullname" . }}
  labels:
    {{- include "cardano.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cardano.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "cardano.fullname" . }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.ports.metrics.port }}"
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cardano.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "cardano.pod" . | nindent 6 }}
  volumeClaimTemplates:
    - metadata:
        name: {{ template "cardano.fullname" . }}
      spec:
        accessModes: {{ .Values.persistence.accessModes }}
        storageClassName: {{ .Values.persistence.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        {{- with .Values.persistence.selectorLabels }}
        selector:
          matchLabels:
          {{ toYaml . | indent 10 }}
        {{- end }}

